name: tcmprobate
favicon: null
layout_spectrum: 0.6700122363399714
typography_spectrum: 0.5982070292811841
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5121742389164865
  lightness: 0.6226760700810701
  saturation: 0.7015725243836641
  rhythmicContrast: 0.22760366555303335
purpose: []
